version: "3.9"
services:
    web_server:
        hostname: web_server
        build:
            context: ./cotizacion-bna
        ports:
            - 5000:5000
    script:
        depends_on:
            - web_server
        build:
            context: ./script
        environment:
            - MONEDA=usd
            - URL=web_server
            - PORT=5000
        hostname: script
        restart: always
        volumes:
            - ./sync:/app/sync
